#!/bin/csh
{% if pbs.header -%}
{{ pbs.header }}
{% endif -%}
{% if pbs.queue -%}
#PBS -q {{ pbs.queue }}
{% endif -%}
#PBS -o ./error/out
#PBS -e ./error/err
#PBS -l nodes={{ nodes_per_job }}:ppn={{ cpus_per_node }}
#PBS -l walltime=12:00:00
#PBS -N {{ jobname }}

cd $PBS_O_WORKDIR

mkdir -p error

@ ncpus  = {{ nodes_per_job * cpus_per_node }}
@ cntmax = {{ num_windows }}
if ( $icnt < $cntmax / 2 ) then
    @ pcnt   = $icnt + 1
    @ ncnt   = $icnt - 1
else
    @ pcnt   = $icnt - 1
    @ ncnt   = $icnt + 1
endif

if ( $cntmax > $ncnt ) qsub -N {{ jobname }}_$ncnt -v icnt=$ncnt -W depend=afterok:$PBS_JOBID run.pbs

set target = `echo "{{ refvalue|default(0.0) }} - {{ delta }} / 2 + ( $icnt % 2 - $pcnt % 2 ) * ( {{ delta }} * $icnt / 2 )" | bc`
sed -e 's/$step/'$icnt'/g' -e 's/$target/'$target'/g' namd.conf > input.$icnt.conf

if ( $icnt > 0 ) then
    python prepare.py input.$pcnt.dcd input.$icnt.pdb $target
endif

{% if use_rest %}
{{ restdir }}/charmrun +p$ncpus {{ restdir }}/namd2 input.$icnt.conf > input.$icnt.log
{% else %}
{{ namddir }}/charmrun +p$ncpus {{ namddir }}/namd2 input.$icnt.conf > input.$icnt.log
{% endif %}
